#ifndef RAYTRACINGSDL__CONSTANTS_H_
#define RAYTRACINGSDL__CONSTANTS_H_

#define WIDTH 640
#define HEIGHT 480
#define BACKGROUND 0x7D8570
#define FOREGROUND 0xAFBE8F
#define ASPECT ((double) WIDTH / HEIGHT)
#endif //RAYTRACINGSDL__CONSTANTS_H_
