#ifndef RAYTRACINGSDL__CONSTANTS_H_
#define RAYTRACINGSDL__CONSTANTS_H_

#define WIDTH (640)
#define HEIGHT (480)
#define BACKGROUND 0x7D, 0x85, 0x70
#define FOREGROUND 0xAF, 0xBE, 0x8F
#define ASPECT ((double) WIDTH / HEIGHT)
#endif //RAYTRACINGSDL__CONSTANTS_H_
